source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/ipapamagic/IPaPods.git'
use_frameworks!

target 'IPaPickerUI_Example' do
  pod 'IPaPickerUI', :path => '../'

  target 'IPaPickerUI_Tests' do
    inherit! :search_paths

    
  end
end
